### ISSUE TITLE
Enable average rating only for specific forums

### ISSUE THREAD

**Issue by Eldenroot** [Darth-Apple/Average-Profile-Ratings#4]
Would be nice to add a new setting to select from which forums will be calculated (I would like to ignore some forums/categories in my board).

**Comment by Eldenroot** [comment]
OK, this is already implemented... am I right? If not, feel free to reopen it :)

**Comment by Darth-Apple** [comment]
Yep, correct. It's implemented. Thanks for the suggestion though! 👍
